# ---------------------------------------------------------------
# Site Settings
# ---------------------------------------------------------------
title: JJ`s Blog
subtitle: Solving Blog
description:
author: JaeJin
language: ko
email: 
url: "https://wlswo.github.io"
baseurl: ""

# ---------------------------------------------------------------
# Build Settings
# ---------------------------------------------------------------
markdown: kramdown
kramdown:
  input: GFM
highlighter: rouge

# Pagination
paginate: 7
paginate_path: "/page:num/"

# Plugins
plugins:
  - jemoji
  - jekyll-sitemap
  - jekyll-feed

# ---------------------------------------------------------------
# Exclude
# ---------------------------------------------------------------
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - README.md
  - Rakefile
  - changelog.md
  - README_en.md

# ---------------------------------------------------------------
# Custom Settings
# ---------------------------------------------------------------
# Add any theme-specific settings here if needed in the future.